# Antes de fazer a requisição, certifique-se de ter instalado o plugin REST Client no Visual Studio Code.
# Para realizar uma requesição, é necessário passar um token de autenticação no header da mesma. Para obter o token, faça o login com um usuário já cadastrado no sistema.
# Como exemplo, faça a requisição de login (auth/login) com o usuário 1234567890 e senha 123123. O token retornado deve ser passado no header de todas as requisições.

### login
POST http://localhost:3001/auth/login
content-type: application/json

{
    "username": "1234567890",
    "password": "123123"
}

### lista de usuários
GET http://localhost:3001/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### usuário específico
GET http://localhost:3001/users/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cadastro de usuário
POST http://localhost:3001/users
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "name": "João Jeefer da Silva Félix",
    "username": "1234567890",
    "password": "123123",
    "email": "joao.jeefer@gmail.com",
    "phone": "1234567890",
    "roleId": 1,
    "shiftId": 2,
    "street": "Rua dos ministérios",
    "number": 10,
    "zipCode": "95765000",
    "city": "Porto Alegre",
    "state": "RS"
}

### lista de papéis / tipo de usuário
GET http://localhost:3001/roles
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cadastro de papel / tipo de usuário
POST http://localhost:3001/roles
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "description": "manutencao"
}

### lista de turnos
GET http://localhost:3001/shifts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cadastro de turno
POST http://localhost:3001/shifts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "description": "noite",
    "start": "2001-01-01T22:00:00.000Z",
    "end": "2001-01-01T06:00:00.000Z"
}

### lista de máquinas
GET http://localhost:3001/machines
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### máquina específica
GET http://localhost:3001/machines/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cadastro de máquina
POST http://localhost:3001/machines
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "description": "Máquina de teste 1",
    "localization": "Setor B"
}

### lista de métricas de máquina
GET http://localhost:3001/metrics/machine/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cadastro de métrica de máquina
POST http://localhost:3001/metrics/machine
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "machineId": 1,
    "availability": 100,
    "performance": 100,
    "quality": 100,
    "oee": 100,
    "scheduledTime": 100,
    "productionTime": 100,
    "productionTheoricTIme": 100,
    "downtime": 100,
    "partsProduced": 100,
    "partsDiscarded": 100,
    "date": "2021-07-19T00:00:00.000Z"
}

### get de todas as ordens de produção
GET http://localhost:3001/production-order/2
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

### cria uma nova ordem de produção
POST http://localhost:3001/production-order
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U

{
    "quantity": 10,
    "status": "Pending",
    "executionDate": "2021-07-19T00:00:00.000Z",
    "creationDate": "2021-07-19T00:00:00.000Z",
    "description": "teste",
    "plannedTime": "2021-07-19T00:00:00.000Z",
    "productId": 1,
    "userId": 1,
}

### get de todos os sensores de produção
GET http://localhost:3001/sensor/1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiMTIzNDU2Nzg5MCIsImlhdCI6MTcyNzc0OTE1NiwiZXhwIjoxNzI3ODM1NTU2fQ.fxr8SRRiBTlFuhlx9pxJDwavGnjqzR_wOz4FQ22F28U
